# Generated by Django 5.2.4 on 2025-07-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_taskentry_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectentry',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
