# Generated by Django 5.2.4 on 2025-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_projectentry_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='task_content',
            field=models.TextField(null=True),
        ),
    ]
