# Generated by Django 5.2.4 on 2025-07-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskentry',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
